SELECT COUNT(*) COUNT
    FROM (
        SELECT ID, GENOTYPE, CONV(GENOTYPE,10, 2) AS CV
            FROM ECOLI_DATA
    ) AS TMP
    WHERE SUBSTRING(CV, LENGTH(CV) - 1, 1) = 0 AND (SUBSTRING(CV, LENGTH(CV) - 2, 1) = 1 OR SUBSTRING(CV, LENGTH(CV), 1))
    
    