# -- 코드를 입력하세요
SELECT 
    YEAR(sales_date) YEAR, 
    MONTH(sales_date) MONTH, 
    COUNT(DISTINCT S.user_id) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT S.user_id) / (
        SELECT COUNT(USER_ID) AS COUNT
        FROM USER_INFO
        WHERE YEAR(JOINED) = 2021
    ),1) AS PUCHASED_RATIO
FROM ONLINE_SALE S
LEFT JOIN USER_INFO U
ON S.USER_ID = U.USER_ID
WHERE YEAR(JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH