-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
LEFT JOIN ICECREAM_INFO AS ICE ON FH.FLAVOR = ICE.FLAVOR
WHERE FH.TOTAL_ORDER >= 3000 AND ICE.INGREDIENT_TYPE = 'fruit_based'
GROUP BY FLAVOR
ORDER BY FH.TOTAL_ORDER DESC