# -- 코드를 입력하세요
# SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE 
# WHERE SALES_DATE LIKE '2022-03%'

# UNION ALL

# SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d'),PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
# FROM OFFLINE_SALE
# WHERE SALES_DATE LIKE '2022-03%'
# ORDER BY SALES_DATE, PRODUCT_ID,USER_ID




SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE like '2022-03%'

UNION ALL

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE like '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

