WITH NO1 AS (
    SELECT *
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/',F.BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS F
JOIN NO1 AS O
ON F.BOARD_ID = O.BOARD_ID
ORDER BY FILE_ID DESC