# SELECT c.CAR_ID
#     , c.CAR_TYPE
#     , ROUND(DAILY_FEE * 30 * (100-DISCOUNT_RATE)/100) as FEE
# FROM CAR_RENTAL_COMPANY_CAR c
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON c.CAR_TYPE = d.CAR_TYPE
# WHERE c.CAR_TYPE in ('세단','SUV')
#     -- 대여 가능한 2022-11-01 ~ 2022-12-01에 대여가 가능한 자동차를 목록을 가져와야하므로 
#     -- NOT IN을 써서 해당 기간에 렌탈 기록이 없는 CAR_ID를 가져와야 한다
# AND c.CAR_ID NOT IN (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE END_DATE >= '2022-11-01' 
#     # AND START_DATE <= '2022-11-30'
# )
# AND DURATION_TYPE = '30일 이상'
# HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

SELECT CAR_ID, C.CAR_TYPE
    , ROUND(daily_fee * 30 * (100-discount_rate)/100) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
        LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON C.CAR_TYPE = D.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단','SUV')
        AND DURATION_TYPE ='30일 이상'
        AND C.CAR_ID NOT IN(
            SELECT CAR_ID	
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE END_DATE >= '2022-11-01'
        )
    HAVING FEE BETWEEN 500000 AND 1999999
    ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC