
SELECT I.REST_ID
    , I.REST_NAME
    , I.FOOD_TYPE
    , i.FAVORITES
    , i.ADDRESS
    , ROUND(AVG(r.REVIEW_SCORE), 2) SCORE
    FROM (
        SELECT *
            FROM REST_INFO
            WHERE ADDRESS LIKE '서울%'
    ) AS I
        INNER JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
    GROUP BY r.REST_ID
    ORDER BY SCORE DESC, FAVORITES DESC