WITH TMP AS ( 
    SELECT REST_ID, AVG(REVIEW_SCORE) AS AVG_SCORE
        FROM REST_REVIEW
        GROUP BY REST_ID
)
SELECT A.REST_ID
    , REST_NAME
    , FOOD_TYPE
    , FAVORITES
    , ADDRESS
    , ROUND(AVG_SCORE,2) AS SCORE
    FROM REST_INFO A
        INNER JOIN  TMP  B
        ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY AVG_SCORE DESC, FAVORITES DESC
;