-- 코드를 입력하세요
# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER,
#     COUNT(DISTINCT O.USER_ID) AS USERS
# FROM ONLINE_SALE AS O
# LEFT JOIN USER_INFO AS U
# ON O.USER_ID = U.USER_ID
# WHERE GENDER IS NOT NULL
# GROUP BY YEAR, MONTH, GENDER
# ORDER BY YEAR, MONTH, GENDER


SELECT YEAR(sales_date) AS YEAR
    , MONTH(sales_date) AS MONTH
    , GENDER
    , COUNT(DISTINCT A.USER_ID) USERS
    FROM ONLINE_SALE A
        LEFT JOIN USER_INFO B
        ON A.user_id = B. user_id
    WHERE GENDER IS NOT NULL
    GROUP BY YEAR, MONTH, GENDER
    ORDER BY YEAR, MONTH, GENDER