-- 코드를 입력하세요
# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER,
#     COUNT(DISTINCT O.USER_ID) AS USERS
# FROM ONLINE_SALE AS O
# LEFT JOIN USER_INFO AS U
# ON O.USER_ID = U.USER_ID
# WHERE GENDER IS NOT NULL
# GROUP BY YEAR, MONTH, GENDER
# ORDER BY YEAR, MONTH, GENDER

SELECT YEAR(s.SALES_DATE) YEAR
    , MONTH(s.SALES_DATE) MONTH
    , u.GENDER
    , COUNT(DISTINCT s.USER_ID) USERS
FROM ONLINE_SALE s
LEFT JOIN USER_INFO u ON s.USER_ID = u.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER