SELECT ROUTE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST),1), 'km') TOTAL_DISTANCE, 
    CONCAT(ROUND(AVG(D_BETWEEN_DIST),2), 'km') AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(sum(D_BETWEEN_DIST),2) DESC






# 노선별로 노선, 총 누계거리 TOTAL_DISTANCE, 평균 역 사이 거리 AVERAGE_DISTANCE
# 총 누계거리 = 역사이의 거리

# SELECT ROUTE
#     , CONCAT(ROUND(SUM(D_BETWEEN_DIST),1), 'km') TOTAL_DISTANCE
#     , CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AVERAGE_DISTANCE
# FROM SUBWAY_DISTANCE
# GROUP BY ROUTE
# ORDER BY TOTAL_DISTANCE desc

