WITH TOTALUSER AS (
    SELECT user_id 
        FROM USER_INFO 
        WHERE YEAR(JOINED) = 2021
)
SELECT YEAR(SALES_DATE) AS _YEAR
    , MONTH(SALES_DATE) AS _MONTH
    , COUNT(DISTINCT S.USER_ID) AS PURCHASED_USER
    , ROUND(COUNT(DISTINCT S.USER_ID)/(SELECT COUNT(USER_ID) FROM TOTALUSER), 1) AS PUCHASED_RATIO
    FROM ONLINE_SALE S
        INNER JOIN TOTALUSER U
        ON S.user_id = U.user_id
    GROUP BY _YEAR, _MONTH
    