-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, 
    SUM(P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE AS OS
LEFT JOIN PRODUCT AS P ON OS.PRODUCT_ID	= P.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE