WITH CAR_H_C as(
    SELECT HISTORY_ID
        , CAR_TYPE
        , DAILY_FEE
        , DATEDIFF(END_DATE, START_DATE) + 1 period
        , CASE WHEN DATEDIFF(END_DATE, START_DATE) >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) >= 7 THEN '7일 이상'
            ELSE NULL
            END DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR c
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
)

SELECT 
    HISTORY_ID
    , CASE WHEN h.DURATION_TYPE is null THEN DAILY_FEE * period
        ELSE ROUND(DAILY_FEE * period * (100-discount_rate)/100) 
        END FEE
FROM CAR_H_C h
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p 
ON h.DURATION_TYPE = p.DURATION_TYPE
AND h.CAR_TYPE = p.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC