WITH NUMBERS ( NUM ) AS (
    SELECT 0 AS NUM
      FROM DUAL
     UNION ALL
    SELECT A.NUM + 1 AS NUM
      FROM NUMBERS A
     WHERE 1=1
       AND A.NUM < 23
 
)
SELECT A.NUM AS HOUR, COUNT(DISTINCT ANIMAL_ID) AS COUNT
    FROM NUMBERS A 
        LEFT JOIN ANIMAL_OUTS B
        ON A.NUM = TO_CHAR(DATETIME, 'HH24')
    GROUP BY A.NUM
    ORDER BY 1