WITH RECURSIVE TblHour AS (
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TblHour
    WHERE HOUR < 23
)
SELECT A.HOUR, IFNULL(COUNT(DISTINCT ANIMAL_ID),0) AS COUNT
    FROM TblHour A
        LEFT JOIN ANIMAL_OUTS B
        ON A.HOUR = HOUR(B.DATETIME)
    GROUP BY A.HOUR