# Write your MySQL query statement below
SELECT ACTIVITY_DATE AS day, COUNT(DISTINCT user_id) AS active_users
FROM Activity
WHERE ACTIVITY_DATE BETWEEN SUBDATE('2019-07-27', 29) AND '2019-07-27'
GROUP BY ACTIVITY_DATE
