SELECT A.WRITER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD A
        INNER JOIN USED_GOODS_USER B
        ON A.WRITER_ID = B.USER_ID
    WHERE STATUS = 'DONE'
    GROUP BY A.WRITER_ID
    HAVING TOTAL_SALES >= 700000
    ORDER BY TOTAL_SALES