# -- 코드를 입력하세요
# SELECT
#     O.PRODUCT_ID,
#     P.PRODUCT_NAME,
#     SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
# FROM FOOD_PRODUCT AS P
# JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
# GROUP BY O.PRODUCT_ID
# ORDER BY TOTAL_SALES DESC, PRODUCT_ID









SELECT P.PRODUCT_ID, PRODUCT_NAME,
    SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID