-- 코드를 입력하세요
SELECT
    ICE.INGREDIENT_TYPE,
    SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS FH
LEFT JOIN ICECREAM_INFO AS ICE ON FH.FLAVOR = ICE.FLAVOR
GROUP BY ICE.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER