-- 코드를 작성해주세요
SELECT g1.ID
    , g1.GENOTYPE
    , g2.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA g1
LEFT JOIN ECOLI_DATA g2 ON g1.PARENT_ID = g2.ID
WHERE g1.PARENT_ID IS NOT NULL
AND g1.GENOTYPE & g2.GENOTYPE = g2.GENOTYPE
ORDER BY ID