-- 누적합 풀이
SELECT MONTH, CAR_ID, RECORDS
FROM (
        SELECT 
            MONTH(START_DATE) AS MONTH
            , CAR_ID 
            , COUNT(START_DATE) AS RECORDS
            , SUM(COUNT(HISTORY_ID)) OVER(PARTITION BY CAR_ID) AS records_sum
        FROM 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE 
            START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
        GROUP BY 
            1,2 
    ) AS TA
WHERE records_sum >= 5
ORDER BY 1 ASC, 2 DESC






# SELECT MONTH(START_DATE) MONTH
#     , CAR_ID
#     , COUNT(HISTORY_ID) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID IN (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE BETWEEN '2022-08-01' and '2022-10-31'
#     GROUP BY CAR_ID
#     HAVING COUNT(HISTORY_ID) >= 5 
# )
# GROUP BY 1,2
# HAVING RECORDS > 0
# ORDER BY MONTH, CAR_ID desc


