-- 코드를 작성해주세요
WITH CODE_SUM as (
    select SUM(CODE)
    from SKILLCODES
    WHERE NAME in ('Python','C#')
)
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT * FROM CODE_SUM)
ORDER BY ID