SELECT PRICE_GROUP*10000 AS PRICE_GROUP, COUNT(product_id) AS PRODUCTS
    FROM (
        SELECT product_id, price DIV 10000 as PRICE_GROUP
            FROM PRODUCT
    ) AS A
    GROUP BY PRICE_GROUP
    ORDER BY PRICE_GROUP